import "server-only";
import {z} from "zod";import {createCalendarEvent,getCalendarOverview} from "@repo/database";import type {KairosToolDefinition} from "./types";
export function buildKairosCalendarTools():KairosToolDefinition[]{// eslint-disable-next-line @typescript-eslint/no-explicit-any
 const tools:Array<KairosToolDefinition<any,any>>=[
 {name:"scheduleTomorrowMeeting",description:"Schedule a meeting tomorrow",requiredRole:"Sales",schema:z.object({title:z.string().default("Meeting"),hour:z.number().int().min(0).max(23).optional()}),execute:async(ctx,input)=>{const now=new Date();const start=new Date(now);start.setDate(start.getDate()+1);start.setHours(input.hour??10,0,0,0);const end=new Date(start);end.setMinutes(end.getMinutes()+30);return{event:await createCalendarEvent({workspaceId:ctx.workspaceId,userId:ctx.userId,title:input.title,startsAt:start.toISOString(),endsAt:end.toISOString(),category:"meeting",status:"scheduled"})};}},
 {name:"summarizeTodaysCalendar",description:"Summarize today's calendar",requiredRole:"Sales",schema:z.object({}),execute:async(ctx)=>{const data=await getCalendarOverview({workspaceId:ctx.workspaceId});return{count:data.today.length,summary:data.today.map(e=>`${e.title} at ${new Date(e.startsAt).toLocaleTimeString()}`).join("; ")||"No events scheduled today.",events:data.today};}},
 {name:"findCalendarAvailability",description:"Find a free time for everyone",requiredRole:"Sales",schema:z.object({date:z.string().optional()}),execute:async(ctx,input)=>{const data=await getCalendarOverview({workspaceId:ctx.workspaceId});const date=input.date?new Date(input.date):new Date(Date.now()+86400000);const day=data.events.filter(e=>new Date(e.startsAt).toDateString()===date.toDateString());return{date:date.toISOString().slice(0,10),busy:day.map(e=>({title:e.title,startsAt:e.startsAt,endsAt:e.endsAt})),suggestion:"09:00-09:30 or 15:00-15:30"};}},
 {name:"prepareMeetingAgenda",description:"Prepare an agenda for a meeting",requiredRole:"Sales",schema:z.object({eventId:z.string().uuid().optional(),topic:z.string().optional()}),execute:async(ctx,input)=>{const data=await getCalendarOverview({workspaceId:ctx.workspaceId});const event=input.eventId?data.events.find(e=>e.id===input.eventId):data.upcoming[0];return{title:event?.title??input.topic??"Meeting agenda",agenda:["Objectives and desired outcome","Progress and blockers","Decisions needed","Action items and owners"]};}},
 {name:"scheduleFollowUpMeeting",description:"Schedule a follow-up meeting",requiredRole:"Sales",schema:z.object({title:z.string().default("Follow-up meeting"),daysFromNow:z.number().int().min(1).max(90).default(7)}),execute:async(ctx,input)=>{const start=new Date();start.setDate(start.getDate()+input.daysFromNow);start.setHours(10,0,0,0);const end=new Date(start);end.setMinutes(end.getMinutes()+30);return{event:await createCalendarEvent({workspaceId:ctx.workspaceId,userId:ctx.userId,title:input.title,startsAt:start.toISOString(),endsAt:end.toISOString(),category:"meeting"})};}},
 ];return tools;}
