import type { KairosAction } from "./types";

/** Static catalog — navigation, creates, insights, external. */
export const KAIROS_ACTION_CATALOG: KairosAction[] = [
  {
    id: "open-crm",
    kind: "navigate",
    label: "Open CRM",
    description: "Pipeline, contacts, and deals",
    confirmation: "Opening CRM...",
    href: "/crm",
    keywords: ["open crm", "crm", "pipeline", "sales"],
    modules: ["crm", "deals", "customers"],
  },
  {
    id: "open-inbox",
    kind: "navigate",
    label: "Open Inbox",
    description: "AI Inbox threads and tasks",
    confirmation: "Opening Inbox...",
    href: "/inbox",
    keywords: ["open inbox", "inbox", "email", "mail"],
    modules: ["inbox"],
  },
  {
    id: "open-analytics",
    kind: "navigate",
    label: "Open Analytics",
    description: "Workspace performance",
    confirmation: "Opening Analytics...",
    href: "/analytics",
    keywords: ["open analytics", "analytics", "insights", "metrics", "reports"],
    modules: ["analytics", "dashboard"],
  },
  {
    id: "open-customers",
    kind: "navigate",
    label: "Open Customers",
    description: "Customer directory",
    confirmation: "Opening Customers...",
    href: "/customers",
    keywords: ["open customers", "customers", "clients", "contacts", "people"],
    modules: ["customers", "crm"],
  },
  {
    id: "open-deals",
    kind: "navigate",
    label: "Open Deals",
    description: "CRM deals pipeline",
    confirmation: "Opening Deals...",
    href: "/deals",
    keywords: ["open deals", "deals", "deal pipeline"],
    modules: ["deals", "crm"],
  },
  {
    id: "open-settings",
    kind: "navigate",
    label: "Open Settings",
    description: "Workspace settings",
    confirmation: "Opening Settings...",
    href: "/settings",
    keywords: ["open settings", "settings", "preferences"],
    modules: ["settings"],
  },
  {
    id: "open-marketing",
    kind: "external",
    label: "Open Advora",
    description: "Launch Advora AI marketing platform",
    confirmation: "Opening Advora...",
    href: "/marketing",
    externalUrl: "https://useadvora.com",
    keywords: [
      "open marketing",
      "open advora",
      "marketing",
      "advora",
      "campaigns",
    ],
    modules: ["marketing"],
    requiresConfirmation: true,
    danger: false,
    confirmTitle: "Leave VanderBase?",
    confirmBody:
      "Kairos will open Advora (useadvora.com) in this tab. Unsaved work on this page may be lost.",
    slash: "advora",
  },
  {
    id: "open-dashboard",
    kind: "navigate",
    label: "Open Dashboard",
    description: "Workspace home",
    confirmation: "Opening Dashboard...",
    href: "/dashboard",
    keywords: ["open dashboard", "dashboard", "home", "overview"],
    modules: ["dashboard"],
  },
  {
    id: "open-calendar",
    kind: "navigate",
    label: "Open Calendar",
    description: "Meetings and bookings",
    confirmation: "Opening Calendar...",
    href: "/calendar",
    keywords: ["open calendar", "calendar", "meetings", "schedule"],
    modules: ["calendar"],
  },
  {
    id: "create-customer",
    kind: "create",
    label: "Create Customer",
    description: "Add a contact to CRM",
    confirmation: "Creating customer...",
    href: "/customers",
    createEntity: "customer",
    keywords: [
      "create customer",
      "add customer",
      "new customer",
      "create contact",
      "add contact",
    ],
    modules: ["customers", "crm"],
    slash: "customer",
    plus: "customer",
  },
  {
    id: "create-deal",
    kind: "create",
    label: "Create Deal",
    description: "Add a deal to the pipeline",
    confirmation: "Creating deal...",
    href: "/deals",
    createEntity: "deal",
    keywords: ["create deal", "add deal", "new deal"],
    modules: ["deals", "crm"],
    slash: "deal",
    plus: "deal",
  },
  {
    id: "create-task",
    kind: "create",
    label: "Create Task",
    description: "Add an inbox follow-up task",
    confirmation: "Creating task...",
    href: "/inbox/tasks",
    createEntity: "task",
    keywords: [
      "create task",
      "add task",
      "new task",
      "create follow up",
      "create follow-up",
      "follow up",
    ],
    modules: ["inbox"],
    slash: "task",
    plus: "task",
  },
  {
    id: "create-reminder",
    kind: "create",
    label: "Create Reminder",
    description: "Schedule a follow-up reminder",
    confirmation: "Creating reminder...",
    href: "/inbox/tasks",
    createEntity: "reminder",
    keywords: [
      "create reminder",
      "add reminder",
      "new reminder",
      "remind me",
      "set reminder",
    ],
    modules: ["inbox", "calendar"],
    slash: "reminder",
    plus: "reminder",
  },
  {
    id: "open-notes",
    kind: "create",
    label: "Create Note",
    description: "Capture a note for the current workspace or CRM record",
    confirmation: "Opening notes...",
    href: "/crm/notes",
    createEntity: "note",
    keywords: ["create note", "new note", "add note", "notes"],
    modules: ["crm", "customers", "deals"],
    slash: "note",
    plus: "note",
  },
  {
    id: "open-meeting",
    kind: "create",
    label: "Schedule Meeting",
    description: "Open the workspace calendar",
    confirmation: "Opening calendar...",
    href: "/calendar",
    createEntity: "meeting",
    keywords: ["create meeting", "new meeting", "schedule meeting", "meeting"],
    modules: ["calendar", "crm", "customers", "deals"],
    slash: "meeting",
    plus: "meeting",
  },
  {
    id: "open-invoices",
    kind: "navigate",
    label: "Open Invoices",
    description: "Review finance and invoice activity",
    confirmation: "Opening invoices...",
    href: "/finance/invoices",
    keywords: ["open invoice", "invoices", "invoice", "finance", "show overdue invoices"],
    modules: ["crm", "dashboard", "finance"],
    slash: "invoice",
  },
  {
    id: "open-campaigns",
    kind: "navigate",
    label: "Open Campaigns",
    description: "Create and review marketing content",
    confirmation: "Opening campaigns...",
    href: "/content",
    keywords: ["open campaign", "campaigns", "campaign", "create campaign"],
    modules: ["marketing"],
    slash: "campaign",
  },
  {
    id: "search-customer",
    kind: "search",
    label: "Search Customer",
    description: "Find customers across the workspace",
    confirmation: "Searching customers...",
    searchQuery: "",
    href: "/customers",
    keywords: ["search customer", "find customer", "lookup customer"],
    modules: ["customers", "crm"],
    slash: "search",
  },
  {
    id: "today-revenue",
    kind: "insight",
    label: "Show Today's Revenue",
    description: "Jump to analytics / pipeline value",
    confirmation: "Opening today's revenue...",
    href: "/analytics?focus=revenue",
    keywords: [
      "show today's revenue",
      "todays revenue",
      "today's revenue",
      "show revenue",
      "revenue today",
      "revenue",
    ],
    modules: ["analytics", "dashboard", "crm"],
  },
  {
    id: "today-signups",
    kind: "insight",
    label: "Show Today's Signups",
    description: "Jump to customers / leads",
    confirmation: "Opening today's signups...",
    href: "/customers?focus=signups",
    keywords: [
      "show today's signups",
      "todays signups",
      "today's signups",
      "show signups",
      "signups today",
      "signups",
    ],
    modules: ["customers", "dashboard", "crm"],
  },
  {
    id: "ask-kairos",
    kind: "ask",
    label: "Ask Kairos",
    description: "Open AI chat",
    confirmation: "Opening Kairos...",
    href: "/chat",
    keywords: ["ask kairos", "open chat", "open kairos"],
    modules: ["chat", "ai"],
  },
  {
    id: "workflow-onboard-lead",
    kind: "workflow",
    label: "Onboard Lead",
    description: "Create customer → deal → follow-up task",
    confirmation: "Starting lead onboarding...",
    workflowId: "onboard-lead",
    keywords: [
      "onboard lead",
      "new lead workflow",
      "create lead flow",
      "onboard customer",
    ],
    modules: ["crm", "customers", "deals"],
    requiresConfirmation: true,
    confirmTitle: "Start lead onboarding?",
    confirmBody:
      "Kairos will walk you through creating a customer, deal, and follow-up task.",
  },
  {
    id: "workflow-daily-pulse",
    kind: "workflow",
    label: "Daily Pulse",
    description: "Revenue → signups → inbox",
    confirmation: "Starting daily pulse...",
    workflowId: "daily-pulse",
    keywords: ["daily pulse", "daily review", "morning briefing"],
    modules: ["dashboard", "analytics"],
  },
];

export function getKairosActionById(id: string): KairosAction | undefined {
  return KAIROS_ACTION_CATALOG.find((action) => action.id === id);
}

export const KAIROS_SUGGESTED_ACTIONS: KairosAction[] = [
  "open-crm",
  "open-inbox",
  "open-customers",
  "open-deals",
  "open-analytics",
  "open-marketing",
  "create-customer",
  "create-deal",
  "create-reminder",
  "open-notes",
  "open-meeting",
  "today-revenue",
]
  .map((id) => getKairosActionById(id)!)
  .filter(Boolean);
