"use server";
import { getUser } from "@repo/auth/server";
import { getMembershipRole } from "@repo/database/workspace";
import { createCalendarEvent, createCalendarMeeting, createCalendarReminder, deleteCalendarEvent, getCalendarOverview, updateCalendarEvent, updateCalendarSettings, upsertCalendarIntegration, upsertCalendarWorkingAvailability } from "@repo/database/calendar-module";
import { createCalendarEventSchema, createCalendarMeetingSchema, createCalendarReminderSchema, updateCalendarEventSchema, updateCalendarAvailabilitySchema } from "@repo/types";
import { resolveActiveWorkspace } from "../../../lib/workspace-context";
export type CalendarActionResult<T>={ok:true;data:T}|{ok:false;error:string};
async function ctx(){const u=await getUser();if(!u)throw new Error("Unauthorized");const c=await resolveActiveWorkspace();if(!c)throw new Error("Workspace required");const r=await getMembershipRole(c.active.workspace.id,u.id);if(!r)throw new Error("Forbidden");return{userId:u.id,workspaceId:c.active.workspace.id};}
function fail(e:unknown):CalendarActionResult<never>{return{ok:false,error:e instanceof Error?e.message:"Calendar action failed"};}
export async function getCalendarModuleData(){const c=await ctx();return{...(await getCalendarOverview({workspaceId:c.workspaceId})),userId:c.userId};}
export async function createCalendarEventAction(input:unknown):Promise<CalendarActionResult<{id:string}>>{try{const c=await ctx();const p=createCalendarEventSchema.parse(input);const e=await createCalendarEvent({workspaceId:c.workspaceId,userId:c.userId,...p});return{ok:true,data:{id:e.id}}}catch(e){return fail(e)}}
export async function updateCalendarEventAction(input:unknown):Promise<CalendarActionResult<{id:string}>>{try{const c=await ctx();const p=updateCalendarEventSchema.parse(input);const {id,...rest}=p;const e=await updateCalendarEvent({workspaceId:c.workspaceId,id,...rest});return{ok:true,data:{id:e.id}}}catch(e){return fail(e)}}
export async function deleteCalendarEventAction(input:{id:string}):Promise<CalendarActionResult<{id:string}>>{try{const c=await ctx();await deleteCalendarEvent({workspaceId:c.workspaceId,id:input.id});return{ok:true,data:{id:input.id}}}catch(e){return fail(e)}}
export async function createCalendarReminderAction(input:unknown):Promise<CalendarActionResult<{id:string}>>{try{const c=await ctx();const p=createCalendarReminderSchema.parse(input);const r=await createCalendarReminder({workspaceId:c.workspaceId,userId:c.userId,...p});return{ok:true,data:{id:r.id}}}catch(e){return fail(e)}}
export async function createCalendarMeetingAction(input:unknown):Promise<CalendarActionResult<{id:string}>>{try{const c=await ctx();const p=createCalendarMeetingSchema.parse(input);const m=await createCalendarMeeting({workspaceId:c.workspaceId,userId:c.userId,...p});return{ok:true,data:{id:m.id}}}catch(e){return fail(e)}}
export async function saveCalendarAvailabilityAction(input:unknown):Promise<CalendarActionResult<{id:string}>>{try{const c=await ctx();const p=updateCalendarAvailabilitySchema.parse(input);const a=await upsertCalendarWorkingAvailability({workspaceId:c.workspaceId,userId:c.userId,...p});return{ok:true,data:{id:a.id}}}catch(e){return fail(e)}}
export async function connectCalendarIntegrationAction(input:{provider:"google"|"outlook"|"apple";accountEmail?:string}):Promise<CalendarActionResult<{id:string}>>{try{const c=await ctx();const i=await upsertCalendarIntegration({workspaceId:c.workspaceId,userId:c.userId,provider:input.provider,accountEmail:input.accountEmail});return{ok:true,data:{id:i.id}}}catch(e){return fail(e)}}
export async function saveCalendarSettingsAction(input:{defaultTimezone?:string;defaultEventDuration?:number}):Promise<CalendarActionResult<{workspaceId:string}>>{try{const c=await ctx();await updateCalendarSettings({workspaceId:c.workspaceId,...input});return{ok:true,data:{workspaceId:c.workspaceId}}}catch(e){return fail(e)}}
