import type { SupabaseClient } from "@supabase/supabase-js";
import type { AiInsight, AnalyticsDashboard, AnalyticsReport, Database, ExecutiveAnalytics, Json } from "@repo/types";
import { createServerClient } from "./server";
import { getFinanceDashboardStats } from "./finance";
import { getCrmDashboardStats } from "./crm";
import { getProjectDashboardStats } from "./projects";

type Client=SupabaseClient<Database>; const clientOrDefault=async(c?:Client)=>c??(await createServerClient()); const obj=(v:unknown)=>v&&typeof v==='object'&&!Array.isArray(v)?v as Record<string,unknown>:{};
function mapDashboard(r:Database["public"]["Tables"]["analytics_dashboards"]["Row"]):AnalyticsDashboard{return{id:r.id,workspaceId:r.workspace_id,createdBy:r.created_by,name:r.name,description:r.description,isDefault:r.is_default,layout:Array.isArray(r.layout)?r.layout as Array<Record<string,unknown>>:[],createdAt:r.created_at,updatedAt:r.updated_at};}
function mapReport(r:Database["public"]["Tables"]["analytics_reports"]["Row"]):AnalyticsReport{return{id:r.id,workspaceId:r.workspace_id,createdBy:r.created_by,name:r.name,reportType:r.report_type,filters:obj(r.filters),data:obj(r.data),generatedAt:r.generated_at,createdAt:r.created_at,updatedAt:r.updated_at};}
function mapInsight(r:Database["public"]["Tables"]["ai_insights"]["Row"]):AiInsight{return{id:r.id,workspaceId:r.workspace_id,createdBy:r.created_by,title:r.title,body:r.body,category:r.category,severity:r.severity,score:r.score,actionUrl:r.action_url,createdAt:r.created_at,updatedAt:r.updated_at};}
export async function listAnalyticsDashboards(input:{workspaceId:string;client?:Client}){const s=await clientOrDefault(input.client);const {data,error}=await s.from("analytics_dashboards").select("*").eq("workspace_id",input.workspaceId).order("updated_at",{ascending:false});if(error)throw new Error(error.message);return(data??[]).map(mapDashboard);}
export async function createAnalyticsDashboard(input:{workspaceId:string;userId:string;name:string;description?:string|null;client?:Client}){const s=await clientOrDefault(input.client);const {data,error}=await s.from("analytics_dashboards").insert({workspace_id:input.workspaceId,created_by:input.userId,name:input.name,description:input.description??null,is_default:true}).select("*").single();if(error||!data)throw new Error(error?.message??"Failed to create dashboard");return mapDashboard(data);}
export async function listAnalyticsReports(input:{workspaceId:string;client?:Client}):Promise<AnalyticsReport[]>{const s=await clientOrDefault(input.client);const {data,error}=await s.from("analytics_reports").select("*").eq("workspace_id",input.workspaceId).order("generated_at",{ascending:false});if(error)throw new Error(error.message);return(data??[]).map(mapReport);}
export async function createAnalyticsReport(input:{workspaceId:string;userId:string;name:string;reportType?:string;data:Record<string,unknown>;client?:Client}):Promise<AnalyticsReport>{const s=await clientOrDefault(input.client);const {data,error}=await s.from("analytics_reports").insert({workspace_id:input.workspaceId,created_by:input.userId,name:input.name,report_type:input.reportType??"executive",data:input.data as Json}).select("*").single();if(error||!data)throw new Error(error?.message??"Failed to create report");return mapReport(data);}
export async function listAiInsights(input:{workspaceId:string;client?:Client}):Promise<AiInsight[]>{const s=await clientOrDefault(input.client);const {data,error}=await s.from("ai_insights").select("*").eq("workspace_id",input.workspaceId).is("dismissed_at",null).order("created_at",{ascending:false}).limit(12);if(error)throw new Error(error.message);return(data??[]).map(mapInsight);}
export async function createAiInsight(input:{workspaceId:string;userId?:string|null;title:string;body:string;category?:string;severity?:AiInsight["severity"];score?:number;actionUrl?:string|null;client?:Client}){const s=await clientOrDefault(input.client);const {data,error}=await s.from("ai_insights").insert({workspace_id:input.workspaceId,created_by:input.userId??null,title:input.title,body:input.body,category:input.category??"business_health",severity:input.severity??"info",score:input.score??null,action_url:input.actionUrl??null}).select("*").single();if(error||!data)throw new Error(error?.message??"Failed to create insight");return mapInsight(data);}
export async function getExecutiveAnalytics(input:{workspaceId:string;client?:Client}):Promise<ExecutiveAnalytics>{const [finance,crm,projects,insights]=await Promise.all([getFinanceDashboardStats(input.workspaceId),getCrmDashboardStats({workspaceId:input.workspaceId}),getProjectDashboardStats({workspaceId:input.workspaceId}),listAiInsights(input)]);const profit=finance.netProfit;const aiScore=Math.round((crm.conversionRate+projects.teamProductivity+Math.min(100,finance.totalRevenue>0?75:25))/3);const health=Math.round((Math.min(100,Math.max(0,profit>0?75:35))+crm.conversionRate+projects.teamProductivity+aiScore)/4);const monthly=finance.monthly.slice(-12).map(p=>({month:p.month,revenue:p.revenue,expenses:p.expenses,profit:p.profit}));const forecastValue=monthly.length?monthly.reduce((a,p)=>a+p.revenue,0)/monthly.length:0;return{revenue:finance.totalRevenue,expenses:finance.totalExpenses,profit,cashFlow:finance.cashBalance,activeCustomers:crm.contacts-crm.leads,leads:crm.leads,conversionRate:crm.conversionRate,projects:projects.activeProjects, tasksCompleted:Math.round(projects.teamProductivity),teamProductivity:projects.teamProductivity,aiScore,businessHealthScore:health,monthly,funnel:[{stage:"lead",count:crm.leads},{stage:"qualified",count:crm.qualifiedLeads},{stage:"open deals",count:crm.openDeals},{stage:"won",count:crm.wonDeals}],insights,forecast:forecastValue?{id:"forecast",workspaceId:input.workspaceId,createdBy:"system",metricKey:"revenue",periodStart:new Date().toISOString().slice(0,10),periodEnd:new Date(new Date().setMonth(new Date().getMonth()+1)).toISOString().slice(0,10),predictedValue:forecastValue,confidence:monthly.length>=3?70:35,methodology:"Average of tracked monthly revenue",createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()}:null};}
export async function generateExecutiveReport(input:{workspaceId:string;userId:string;client?:Client}){const data=await getExecutiveAnalytics(input);return createAnalyticsReport({workspaceId:input.workspaceId,userId:input.userId,name:`Executive report · ${new Date().toISOString().slice(0,10)}`,data:data as unknown as Record<string,unknown>,client:input.client});}
