import type { SupabaseClient } from "@supabase/supabase-js";
import type { CalendarEvent, CalendarEventPriority, CalendarEventStatus, CalendarIntegration, CalendarMeeting, CalendarOverview, CalendarReminder, CalendarSettings, CalendarWorkingAvailability, Database, Json } from "@repo/types";
import { createServerClient } from "./server";

type Client = SupabaseClient<Database>;
const clientOrDefault = async (client?: Client) => client ?? (await createServerClient());
const arr = (v: unknown) => Array.isArray(v) ? v : [];
const obj = (v: unknown) => v && typeof v === "object" && !Array.isArray(v) ? v as Record<string, unknown> : {};
function mapEvent(r: Database["public"]["Tables"]["events"]["Row"]): CalendarEvent { return { id:r.id,workspaceId:r.workspace_id,createdBy:r.created_by,title:r.title,description:r.description,location:r.location,videoUrl:r.video_url,startsAt:r.starts_at,endsAt:r.ends_at,timezone:r.timezone,status:r.status,priority:r.priority,color:r.color,isAllDay:r.is_all_day,recurrenceRule:r.recurrence_rule,category:r.category,createdAt:r.created_at,updatedAt:r.updated_at }; }
function mapMeeting(r: Database["public"]["Tables"]["meetings"]["Row"]): CalendarMeeting { return { id:r.id,workspaceId:r.workspace_id,eventId:r.event_id,createdBy:r.created_by,notes:r.notes,recordingUrl:r.recording_url,summary:r.summary,actionItems:arr(r.action_items) as Array<Record<string,unknown>>,followUpTaskIds:r.follow_up_task_ids??[],createdAt:r.created_at,updatedAt:r.updated_at }; }
function mapReminder(r: Database["public"]["Tables"]["reminders"]["Row"]): CalendarReminder { return { id:r.id,workspaceId:r.workspace_id,createdBy:r.created_by,eventId:r.event_id,title:r.title,remindAt:r.remind_at,channel:r.channel,recurrenceRule:r.recurrence_rule,sentAt:r.sent_at,createdAt:r.created_at,updatedAt:r.updated_at }; }
function mapIntegration(r: Database["public"]["Tables"]["calendar_integrations"]["Row"]): CalendarIntegration { return { id:r.id,workspaceId:r.workspace_id,createdBy:r.created_by,provider:r.provider,accountEmail:r.account_email,externalAccountId:r.external_account_id,status:r.status,lastSyncedAt:r.last_synced_at,syncError:r.sync_error,createdAt:r.created_at,updatedAt:r.updated_at }; }
function mapAvailability(r: Database["public"]["Tables"]["calendar_working_availability"]["Row"]): CalendarWorkingAvailability { return { id:r.id,workspaceId:r.workspace_id,createdBy:r.created_by,name:r.name,timezone:r.timezone,workingDays:obj(r.working_days) as Record<string,boolean>,hours:obj(r.hours) as Record<string,string>,vacationDates:arr(r.vacation_dates).filter((x):x is string=>typeof x==='string'),createdAt:r.created_at,updatedAt:r.updated_at }; }
function mapSettings(r: Database["public"]["Tables"]["calendar_settings"]["Row"]): CalendarSettings { return { workspaceId:r.workspace_id,defaultTimezone:r.default_timezone,weekStartsOn:r.week_starts_on,defaultEventDuration:r.default_event_duration,workingHours:obj(r.working_hours) as Record<string,string>,colorCategories:obj(r.color_categories) as Record<string,string>,notifications:obj(r.notifications) as Record<string,boolean>,createdAt:r.created_at,updatedAt:r.updated_at }; }

export async function listCalendarEvents(input:{workspaceId:string; from?:string; to?:string; status?:CalendarEventStatus; client?:Client}):Promise<CalendarEvent[]> { const s=await clientOrDefault(input.client); let q=s.from("events").select("*").eq("workspace_id",input.workspaceId).order("starts_at",{ascending:true}); if(input.from)q=q.gte("starts_at",input.from); if(input.to)q=q.lte("starts_at",input.to); if(input.status)q=q.eq("status",input.status); const {data,error}=await q; if(error)throw new Error(`Failed to list calendar events: ${error.message}`); return (data??[]).map(mapEvent); }
export async function createCalendarEvent(input:{workspaceId:string;userId:string;title:string;description?:string|null;location?:string|null;videoUrl?:string|null;startsAt:string;endsAt:string;timezone?:string;status?:CalendarEventStatus;priority?:CalendarEventPriority;color?:string;isAllDay?:boolean;recurrenceRule?:string|null;category?:string;client?:Client}):Promise<CalendarEvent>{ const s=await clientOrDefault(input.client); const {data,error}=await s.from("events").insert({workspace_id:input.workspaceId,created_by:input.userId,title:input.title,description:input.description??null,location:input.location??null,video_url:input.videoUrl??null,starts_at:input.startsAt,ends_at:input.endsAt,timezone:input.timezone??"UTC",status:input.status??"scheduled",priority:input.priority??"medium",color:input.color??"#f97316",is_all_day:input.isAllDay??false,recurrence_rule:input.recurrenceRule??null,category:input.category??"general"}).select("*").single(); if(error||!data)throw new Error(`Failed to create event: ${error?.message??"Unknown"}`); return mapEvent(data); }
export async function updateCalendarEvent(input:{workspaceId:string;id:string;title?:string;description?:string|null;location?:string|null;videoUrl?:string|null;startsAt?:string;endsAt?:string;timezone?:string;status?:CalendarEventStatus;priority?:CalendarEventPriority;color?:string;isAllDay?:boolean;recurrenceRule?:string|null;category?:string;client?:Client}):Promise<CalendarEvent>{ const s=await clientOrDefault(input.client); const p:Database["public"]["Tables"]["events"]["Update"]={}; for(const [k,v] of Object.entries({title:input.title,description:input.description,location:input.location,video_url:input.videoUrl,starts_at:input.startsAt,ends_at:input.endsAt,timezone:input.timezone,status:input.status,priority:input.priority,color:input.color,is_all_day:input.isAllDay,recurrence_rule:input.recurrenceRule,category:input.category}))if(v!==undefined)(p as Record<string,unknown>)[k]=v; const {data,error}=await s.from("events").update(p).eq("workspace_id",input.workspaceId).eq("id",input.id).select("*").single(); if(error||!data)throw new Error(`Failed to update event: ${error?.message??"Unknown"}`); return mapEvent(data); }
export async function deleteCalendarEvent(input:{workspaceId:string;id:string;client?:Client}){const s=await clientOrDefault(input.client);const {error}=await s.from("events").delete().eq("workspace_id",input.workspaceId).eq("id",input.id);if(error)throw new Error(`Failed to delete event: ${error.message}`);}
export async function listCalendarMeetings(input:{workspaceId:string;client?:Client}):Promise<CalendarMeeting[]>{const s=await clientOrDefault(input.client);const {data,error}=await s.from("meetings").select("*").eq("workspace_id",input.workspaceId).order("created_at",{ascending:false});if(error)throw new Error(error.message);return(data??[]).map(mapMeeting);}
export async function createCalendarMeeting(input:{workspaceId:string;userId:string;eventId:string;notes?:string|null;recordingUrl?:string|null;summary?:string|null;client?:Client}):Promise<CalendarMeeting>{const s=await clientOrDefault(input.client);const {data,error}=await s.from("meetings").upsert({workspace_id:input.workspaceId,created_by:input.userId,event_id:input.eventId,notes:input.notes??null,recording_url:input.recordingUrl??null,summary:input.summary??null},{onConflict:"event_id"}).select("*").single();if(error||!data)throw new Error(error?.message??"Failed to save meeting");return mapMeeting(data);}
export async function listCalendarReminders(input:{workspaceId:string;client?:Client}):Promise<CalendarReminder[]>{const s=await clientOrDefault(input.client);const {data,error}=await s.from("reminders").select("*").eq("workspace_id",input.workspaceId).order("remind_at",{ascending:true});if(error)throw new Error(error.message);return(data??[]).map(mapReminder);}
export async function createCalendarReminder(input:{workspaceId:string;userId:string;eventId?:string|null;title:string;remindAt:string;channel?:"email"|"push"|"in_app";recurrenceRule?:string|null;client?:Client}):Promise<CalendarReminder>{const s=await clientOrDefault(input.client);const {data,error}=await s.from("reminders").insert({workspace_id:input.workspaceId,created_by:input.userId,event_id:input.eventId??null,title:input.title,remind_at:input.remindAt,channel:input.channel??"in_app",recurrence_rule:input.recurrenceRule??null}).select("*").single();if(error||!data)throw new Error(error?.message??"Failed to create reminder");return mapReminder(data);}
export async function listCalendarIntegrations(input:{workspaceId:string;client?:Client}):Promise<CalendarIntegration[]>{const s=await clientOrDefault(input.client);const {data,error}=await s.from("calendar_integrations").select("*").eq("workspace_id",input.workspaceId).order("provider");if(error)throw new Error(error.message);return(data??[]).map(mapIntegration);}
export async function upsertCalendarIntegration(input:{workspaceId:string;userId:string;provider:"google"|"outlook"|"apple";accountEmail?:string|null;externalAccountId?:string|null;status?:string;client?:Client}):Promise<CalendarIntegration>{const s=await clientOrDefault(input.client);const {data,error}=await s.from("calendar_integrations").upsert({workspace_id:input.workspaceId,created_by:input.userId,provider:input.provider,account_email:input.accountEmail??null,external_account_id:input.externalAccountId??null,status:input.status??"connected"},{onConflict:"workspace_id,provider,external_account_id"}).select("*").single();if(error||!data)throw new Error(error?.message??"Failed to save integration");return mapIntegration(data);}
export async function getCalendarWorkingAvailability(input:{workspaceId:string;client?:Client}):Promise<CalendarWorkingAvailability|null>{const s=await clientOrDefault(input.client);const {data,error}=await s.from("calendar_working_availability").select("*").eq("workspace_id",input.workspaceId).limit(1).maybeSingle();if(error)throw new Error(error.message);return data?mapAvailability(data):null;}
export async function upsertCalendarWorkingAvailability(input:{workspaceId:string;userId:string;name:string;timezone:string;workingDays:Record<string,boolean>;hours:Record<string,string>;vacationDates?:string[];client?:Client}):Promise<CalendarWorkingAvailability>{const s=await clientOrDefault(input.client);const {data,error}=await s.from("calendar_working_availability").upsert({workspace_id:input.workspaceId,created_by:input.userId,name:input.name,timezone:input.timezone,working_days:input.workingDays,hours:input.hours,vacation_dates:input.vacationDates??[]},{onConflict:"id"}).select("*").single();if(error||!data)throw new Error(error?.message??"Failed to save availability");return mapAvailability(data);}
export async function getCalendarSettings(input:{workspaceId:string;client?:Client}):Promise<CalendarSettings>{const s=await clientOrDefault(input.client);const {data,error}=await s.from("calendar_settings").select("*").eq("workspace_id",input.workspaceId).maybeSingle();if(error)throw new Error(error.message);if(data)return mapSettings(data);const {data:created,error:createError}=await s.from("calendar_settings").insert({workspace_id:input.workspaceId}).select("*").single();if(createError||!created)throw new Error(createError?.message??"Failed to create settings");return mapSettings(created);}
export async function updateCalendarSettings(input:{workspaceId:string;defaultTimezone?:string;weekStartsOn?:number;defaultEventDuration?:number;workingHours?:Record<string,string>;colorCategories?:Record<string,string>;notifications?:Record<string,boolean>;client?:Client}):Promise<CalendarSettings>{const s=await clientOrDefault(input.client);await getCalendarSettings(input);const p:Database["public"]["Tables"]["calendar_settings"]["Update"]={};if(input.defaultTimezone!==undefined)p.default_timezone=input.defaultTimezone;if(input.weekStartsOn!==undefined)p.week_starts_on=input.weekStartsOn;if(input.defaultEventDuration!==undefined)p.default_event_duration=input.defaultEventDuration;if(input.workingHours!==undefined)p.working_hours=input.workingHours as Json;if(input.colorCategories!==undefined)p.color_categories=input.colorCategories as Json;if(input.notifications!==undefined)p.notifications=input.notifications as Json;const {data,error}=await s.from("calendar_settings").update(p).eq("workspace_id",input.workspaceId).select("*").single();if(error||!data)throw new Error(error?.message??"Failed to update settings");return mapSettings(data);}
export async function getCalendarOverview(input:{workspaceId:string;client?:Client}):Promise<CalendarOverview>{const events=await listCalendarEvents(input);const meetings=await listCalendarMeetings(input);const reminders=await listCalendarReminders(input);const availability=await getCalendarWorkingAvailability(input);const settings=await getCalendarSettings(input);const now=new Date();const end=new Date(now);end.setDate(end.getDate()+14);const today=events.filter(e=>new Date(e.startsAt).toDateString()===now.toDateString());return{events,today,upcoming:events.filter(e=>new Date(e.startsAt)>=now&&new Date(e.startsAt)<=end&&e.status!=="cancelled"),reminders,meetings,availability,settings};}
